version: "2.1"
services:
  rabbitmq:
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: greenapimq
    restart: always
    environment:
      - RABBITMQ_CONFIG_FILE=./rabbitmq.conf
      - RABBITMQ_CONF_ENV_FILE=./rabbitmq-env.conf
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      - ./logs/:/var/log/rabbitmq
    ports:
      - 5672:15672 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  m1:
    build: 
      context: m1-service
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    depends_on:
      rabbitmq:
        condition: service_healthy
  m2:
    build: 
      context: m2-service
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

