version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: greenapimq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=gapi_user
      - RABBITMQ_DEFAULT_PASS=gapi_password
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:15672 
  m1:
    build: 
      context: .
      dockerfile: ./m1-service/Dockerfile
    ports:
      - 5000:3000
    depends_on:
      - rabbitmq
  m2:
    build: 
      context: .
      dockerfile: ./m2-service/Dockerfile
    ports:
      - 6000:3000
    depends_on:
      - rabbitmq

